(function ($) {
      $.CheckForm.aUsages = 
 {
  "int":"^([+-]?)\\d+$",          
  "int+":"^([+]?)\\d+$",          
  "int-":"^-\\d+$",           
  "num":"^[0-9]+$",       
  "num+":"^([+]?)\\d*\\.?\\d+$",        
  "num-":"^-\\d*\\.?\\d+$",         
  "float":"^([+-]?)\\d*\\.\\d+$",        
  "float+":"^([+]?)\\d*\\.\\d+$",   
  "floatmn":"^([+]?)\\d{m}\\.\\d{0,n}$",     
  "float-":"^-\\d*\\.\\d+$",                  
  "email":"^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$",
  "color":"^#[a-fA-F0-9]{6}",        
  "url":"^http[s]?:\\/\\/([\\w-]+\\.)+[\\w-]+([\\w-./?%&=]*)?$",
  "chinese":"^[\\u4E00-\\u9FA5\\uF900-\\uFA2D]+$",   
  "ascii":"^[\\x00-\\xFF]+$",         
  "zipcode":"^\\d{6}$",           
  "mobile":"^[1-9][0-9]{10}$",    
  "ip4":"^\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}.\\d{1,3}$", 
  "notempty":"^\\S+$",      
  "picture":"(.*)\\.(jpg|bmp|gif|ico|pcx|jpeg|tif|png|raw|tga)$", 
  "rar":"(.*)\\.(rar|zip|7zip|tgz)$",       
  "date":"^\\d{4}(\\-|\\/|\.)\\d{1,2}\\1\\d{1,2}$",        
  "text":"^[A-Za-z\\u4e00-\\u9fa5\\uF900-\\uFA2D]+$",       
  "text0":"^[u4e00-u9fa5]+$",       
  "text1":"^[A-Za-z0-9\\u4E00-\\u9FA5\\uF900-\\uFA2D]+$",       
  "text2":"^[A-Za-z0-9\\u4E00-\\u9FA5\\uF900-\\uFA2D_-]+$",       
  "text3":"^[\\u4E00-\\u9FA5\\uF900-\\uFA2D,，]+$",      
  "text4":"^[A-Za-z0-9\\u4e00-\\u9fa5\\uF900-\\uFA2D|\\s]+$",     
  "text5":"^[A-Za-z0-9\\u4e00-\\u9fa5\\uF900-\\uFA2D_-|\\s]+$",       
  "text6":"^[\\u4e00-\\u9fa5\\uF900-\\uFA2D,，|\\s]+$",  
  "tel":"^[1-9]+[-]?[0-9]+$",   
  "qq":"^\\w+((-\\w+)|(\\.\\w+))*\\@[A-Za-z0-9]+((\\.|-)[A-Za-z0-9]+)*\\.[A-Za-z0-9]+$|^[1-9]+[0-9]*$",    
  "licence":"^[A-Za-z0-9]+$"  
 };
  $.CheckForm.aUsagesTxt =
 {
     "mustinput": "不能为空",
     "mustselect": "必选",
     "mustchecked": "必选",
     "minSize": "字符长度最小为{0}",
     "maxSize": "字符长度最大为{0}",
     "min": "必须大于{0}",
     "max": "必须小于{0}",
     "maxCheckbox": "最多选择{0}个",
     "minCheckbox": "至少选择{0}个",
     "equals": "必须与{0}相等",
     "maxDate": "日期不能大于{0}",
     "minDate": "日期不能小于{0}", 
  "int":"整数",
  "int+":"正整数",
  "int-":"负整数",
  "num":"数字",
  "num+":"正数",
  "num-":"负数",
  "float":"浮点数",
  "float+":"正浮点数",
  "float-":"负浮点数 ",           
  "email":"邮件,例：zhenlong@zhenglong.com",
  "color":"颜色",
  "url":"联接,例：http://www.loonyee.com",
  "chinese":"仅中文",
  "ascii":"仅ACSII字符",
  "zipcode":"邮编",
  "mobile":"手机",
  "ip4":"ip地址",
  "notempty":"非空",
  "picture":"图片",
  "rar":"压缩文件",
  "date":"日期",
  "text":"中英文",
  "text0":"中文",
  "text1":"中英文和数字",
  "text2":"中英文,数字,-",
  "text3":"中英和','",
  "text4":"中英文,数字和空格",
  "text5":"中英文,数字,-和空格",
  "text6":"中文,',',和空格",
  "tel":"数字,-",
  "qq":"qq",
  "licence":"营业号"
 };
})(jQuery);
